/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package road.rush;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.math.*;
import javax.swing.*;

/**
 *
 * @author Mahadi Hassan
 */
public class fPlay extends javax.swing.JFrame {

    /**
     * Creates new form fPlay
     */
    //-------------------------
    int x,y,c;
    boolean mid=false;
    boolean left=false;
    boolean right=false;
    
    
    
    public int ran(){
        int r= (int) (Math.random()*(4-1)+1);
        return r;
    }
    
    public void left(){
        System.out.println("left");
        car.setLocation(25, 430);
        left=true;
        right=false;
        mid=false;  
    }
        
    public void right(){
        System.out.println("Right");
        car.setLocation(285, 430);
        right=true;
        mid=false;
        left=false;        
    }
    
    public void mid(){
        car.setLocation(155, 430);
        System.out.println("\tmid");
        mid=true;
        right=false;
        left=false;
    }
    //45 175 305
    public void fn(){
        switch (ran()) {
            case 1:
                x=45;
                break;
            case 2:
                x=175;
                break;
            case 3:
                x=305;
                break;
            default:
                break;
        }

        //x=45;
        y=-20;
        JPanel a=new JPanel();
        a.setBackground(Color.red);
        a.setSize(40, 60);
        jPanel5.add(a);
        
        
        Thread t = new Thread(){
            public void run(){
                for(; ;){
                    try {
                        sleep(10);
                    } catch (Exception e) {
                    }
                    //--
                    a.setLocation(x,y);
                    y+=5;
                    c=y;
                    System.out.println(x+"x / y"+"     r="+ran());
                    
//                    if (c==10){
//                        c=0;
//                        fn();
//                    }
                    if(y==400){
                        y=-20;
                        fn();
                        break;
                    }
                    
                    //--
                }
            }
        };
        t.start();
        
    }
    
    //-------------------------
    
    
    
    public fPlay() {
        initComponents();
        car.setLocation(155, 430);
        jPanel5.add(car);
        fn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        car = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Road Rush");
        setBounds(new java.awt.Rectangle(400, 100, 0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        car.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout carLayout = new javax.swing.GroupLayout(car);
        car.setLayout(carLayout);
        carLayout.setHorizontalGroup(
            carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        carLayout.setVerticalGroup(
            carLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(395, Short.MAX_VALUE)
                .addComponent(car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            if (!right) {
                left();
            }
            else {
                mid();   
            }
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            if(!left){
                right();
            }
            else{
                mid();
            }
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            System.out.println(ran());
            fn();
        }
        
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel car;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
